_wandb:
    value:
        cli_version: 0.21.0
        e:
            bvu08gwxwgmk9liteqmpr2600jk3j1kq:
                codePath: dev_notebooks\black_scholes\pinn_black_scholes.ipynb
                codePathLocal: pinn_black_scholes.ipynb
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "2022669545472"
                        used: "1022437748736"
                email: toby.safie@gmail.com
                executable: c:\Users\tobys\miniconda3\envs\star-pinn\python.exe
                git:
                    commit: bcdee3993527b03c9fc41ad4c71faa9adbccd22c
                    remote: https://github.com/tobiassafie/STAR.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-a306856b-3d1f-329a-4622-5e45cf6837bb
                host: MAUMAU
                memory:
                    total: "68407418880"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\tobys\Desktop\STAR\dev_notebooks\black_scholes\pinn_black_scholes.ipynb
                python: CPython 3.10.18
                root: c:\Users\tobys\Desktop\STAR\dev_notebooks\black_scholes
                startedAt: "2025-07-15T17:48:33.985489Z"
                writerId: bvu08gwxwgmk9liteqmpr2600jk3j1kq
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
activation:
    value: relu
hidden_layers:
    value: 8
neurons_per_layer:
    value: 256
