wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 2.3223117986713744
hidden_layers:
  value: 8
ic_weight_scale:
  value: 3.8180678037820552
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.1778917690884336
