wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 8.812427693736774
hidden_layers:
  value: 8
ic_weight_scale:
  value: 9.366852407526752
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.22222017349072676
