wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.4470310323310822
hidden_layers:
  value: 8
ic_weight_scale:
  value: 2.473462854535936
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 6.870287670452619
