wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 5.636220905362624
hidden_layers:
  value: 8
ic_weight_scale:
  value: 2.697982302413325
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 4.195372180166474
