wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.0893986599907384
hidden_layers:
  value: 8
ic_weight_scale:
  value: 3.328158371444897
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 3.0854558191932164
