wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.3952525470223016
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.10791977894169189
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 5.49461101513194
