wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.13360581703301594
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.05485836902428156
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 10.674860479298047
