wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.6377644286837456
hidden_layers:
  value: 6
ic_weight_scale:
  value: 2.1224772755362253
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 5.664296495829101
