wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.41123118132923264
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.08592053877083604
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 14.459434734080595
