wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.8197054159679781
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.061005910040264934
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 13.951551072349249
