wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.641443445362633
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.05283658444962415
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 9.09721662852388
