wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.24759482373855785
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.05378985846288301
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 14.109555569471253
