wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.757579349775196
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.4509568589751368
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 5.01492765318148
