wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 2.025041466816032
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.051688994878319745
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 6.546218501408915
