wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.6813706299260899
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.06114557165119223
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 7.892454965443275
