wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.3535451931530686
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.05080732815230281
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 7.5633719492554095
