wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.39136658788189266
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.33998365190562285
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 7.367408401980235
