wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.150759304013193
hidden_layers:
  value: 6
ic_weight_scale:
  value: 1.9660196528449565
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 14.357546609418982
