wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.9773598889079382
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.36822735151508496
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 7.801056134046477
