wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.7717061299293331
hidden_layers:
  value: 6
ic_weight_scale:
  value: 0.057363040580818904
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 32
pde_weight_scale:
  value: 7.906436041561116
