wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 6
learning_rate:
  value: 0.0010131573479054854
neurons_per_layer:
  value: 128
num_epochs:
  value: 5000
w_boundary:
  value: 1
w_pde:
  value: 1
w_terminal:
  value: 1
