wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.431684316823106
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.21848042268655127
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.23054143537192703
