wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.6413203437022277
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.11071831616412332
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.21386726246918464
