wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.10394394162358156
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.10630533043503725
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 7.152293865538184
