wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.14753496185660894
hidden_layers:
  value: 8
ic_weight_scale:
  value: 5.226032026238329
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 1.6449402452619648
