wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.4642639644246355
hidden_layers:
  value: 8
ic_weight_scale:
  value: 1.8345222783543291
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 1.843773900534189
