wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.36355922093910537
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.1700776260211924
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.30811339696341383
