wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.110232774789058
hidden_layers:
  value: 8
ic_weight_scale:
  value: 8.110222353855672
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.19689882622124524
