wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.10859311010701168
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.2793943502147533
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 2.7549161558767756
