wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.14273589855710314
hidden_layers:
  value: 8
ic_weight_scale:
  value: 1.1989691115581027
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 1.4268033097010977
