wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.13898367355916164
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.1605277220808656
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.17079892871844587
