wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.2192578766115385
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.8020339547840126
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 9.898074505356195
