wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.268123197426473
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.5658821577913733
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 3.38206615984475
