wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.20596628195829575
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.4581104630222648
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.12264177731322
