wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.25847969586763914
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.28823108224786037
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 0.32386689460077533
