wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 4
learning_rate:
  value: 0.0024
neurons_per_layer:
  value: 32
num_epochs:
  value: 5000
w_boundary:
  value: 0.030415616620302996
w_pde:
  value: 2.4833515348975026
w_terminal:
  value: 0.10978492181501127
