wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 4
learning_rate:
  value: 0.0024
neurons_per_layer:
  value: 32
num_epochs:
  value: 5000
w_boundary:
  value: 0.01503424002746584
w_pde:
  value: 6.189247973487179
w_terminal:
  value: 0.021483322362924613
