wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 4
learning_rate:
  value: 0.0024
neurons_per_layer:
  value: 32
num_epochs:
  value: 5000
w_boundary:
  value: 0.019086097964376193
w_pde:
  value: 6.906168124404092
w_terminal:
  value: 0.003015832406434853
