wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 2
learning_rate:
  value: 0.0024
neurons_per_layer:
  value: 256
num_epochs:
  value: 5000
w_boundary:
  value: 1.987350967490037
w_pde:
  value: 1.0092601861391348
w_terminal:
  value: 1.901575330612465
