wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 2
learning_rate:
  value: 0.0024
neurons_per_layer:
  value: 256
num_epochs:
  value: 5000
w_boundary:
  value: 1.9955690867082172
w_pde:
  value: 1.0562494095428168
w_terminal:
  value: 1.1386429450437383
