wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 2
learning_rate:
  value: 0.0024
neurons_per_layer:
  value: 256
num_epochs:
  value: 5000
w_boundary:
  value: 0.09222819063533796
w_pde:
  value: 9.188053761149046
w_terminal:
  value: 0.05254829359331053
