wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 0.10477676101200484
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.22607403921850844
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 5.932061795940626
