wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 1.6063404941527126
hidden_layers:
  value: 8
ic_weight_scale:
  value: 0.4816560532098325
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 3.795619262206038
