wandb_version: 1

activation:
  value: relu
bc_weight_scale:
  value: 5.8209318463531385
hidden_layers:
  value: 8
ic_weight_scale:
  value: 1.1201611354102992
init_method:
  value: xavier
initial_lr:
  value: 0.005
neurons_per_layer:
  value: 256
pde_weight_scale:
  value: 1.0568427220983507
