wandb_version: 1

N_boundary:
  value: 500
N_pde:
  value: 2500
N_terminal:
  value: 500
hidden_layers:
  value: 2
learning_rate:
  value: 0.002533553138511793
neurons_per_layer:
  value: 256
num_epochs:
  value: 5000
w_boundary:
  value: 0.9
w_pde:
  value: 10
w_terminal:
  value: 0.04
